drop table bera_size;

CREATE TABLE BERA_SIZE(
BERA_SIZE NVARCHAR2(20),
PRICE NVARCHAR2 (10),
FLAVOR NVARCHAR2(10)
);

INSERT INTO BERA_SIZE
VALUES('파인트','8200원','3가지 맛');
INSERT INTO BERA_SIZE
VALUES('쿼터','15500원','4가지 맛');
INSERT INTO BERA_SIZE
VALUES('패밀리','22000원','5가지 맛');
INSERT INTO BERA_SIZE
VALUES('하프갤런','26500원','6가지 맛');


SELECT * FROM BERA_SIZE;

CREATE TABLE BERA_FLAVOR(
FLAVOR_NAME NVARCHAR2(20)
);

SELECT * FROM BERA_FLAVOR;

drop table BERA_FLAVOR;


INSERT INTO BERA_FLAVOR
VALUES ('슈팅스타');
INSERT INTO BERA_FLAVOR
VALUES ('엄마는 외계인');
INSERT INTO BERA_FLAVOR
VALUES ('바람과 함께 사라지다');
INSERT INTO BERA_FLAVOR
VALUES ('뉴욕치즈케잌');
INSERT INTO BERA_FLAVOR
VALUES ('레인보우샤벳트');
INSERT INTO BERA_FLAVOR
VALUES ('민트초코');

commit;
