DROP TABLE C_SELLER;
DROP TABLE C_MEMBER;

CREATE TABLE C_SELLER( --판매자 DB
 SELLER NVARCHAR2(10), 
 S_NAME NVARCHAR2(20), 
 S_PRICE NUMBER(20), 
 S_RUN NUMBER(20),
 S_DATE NUMBER(20), 
 S_OIL NVARCHAR2(20),
 S_CC NUMBER(5),
 S_COLOR NVARCHAR2(20),
 S_NUMBER NVARCHAR2(20),
 S_PHONE NVARCHAR2(20)
 );
 
 INSERT INTO C_SELLER VALUES ('유현서','현대',707,1005,2015,'휘발유',5000,'흰색','12호1245','01077204452');
 
 SELECT * FROM C_SELLER WHERE S_NAME LIKE '%현%';
 
 COMMIT;
 
 SELECT * FROM C_SELLER WHERE S_NAME LIKE '%Y%';
 
 
 SELECT * FROM C_SELLER;
 SELECT * FROM C_MEMBER;
 SELECT * FROM CAR_GOODS;
 DROP TABLE C_MEMBER;
 CREATE TABLE C_MEMBER( --회원가입할 때 사용하는 DB
  ID NVARCHAR2(10), --아이디
  PW NUMBER(20), --비밀번호
  NAME NVARCHAR2(20), --사용자이름
  AGE NUMBER(20), --나이
  PHONE NVARCHAR2(20), --전화번호
  ADR NVARCHAR2(20),--주소
  E_MAIL NVARCHAR2(20),--이메일
  ANC NVARCHAR2(20)
 );
 
 
--결제 시스템을 위한 DB 



 
 

 