--테이블 데이터는 JSSTU에 있음!!!
--문제는 황교수님이 보내주신 메일에 있음!!

--1조
--1)
SELECT STUNO AS 번호, STUNAME AS 이름 FROM JSSTU 
WHERE STUBIRTH BETWEEN '1995.01.01' AND '1995.12.31';
--2)
ALTER TABLE JSSTU ADD SHOESE NUMBER(2);
SELECT * FROM JSSTU;

UPDATE JSSTU
SET SHOESE = 70
WHERE STUNAME = '이재홍';

UPDATE JSSTU
SET SHOESE = 60
WHERE STUNAME = '유현서';

UPDATE JSSTU
SET SHOESE = 70
WHERE STUNAME = '오형록';

UPDATE JSSTU
SET SHOESE = 80
WHERE STUNAME = '서민재';

SELECT *
FROM JSSTU
WHERE GROUPNO = 6
ORDER BY SHOESE ASC;

--3)
ALTER TABLE JSSTU ADD MERRY NVARCHAR2(1);
SELECT * FROM JSSTU;

UPDATE JSSTU 
SET MERRY = 0
WHERE STUNAME = '유현서';

UPDATE JSSTU 
SET MERRY = 1
WHERE STUNAME = '이재홍';

UPDATE JSSTU 
SET MERRY = 0
WHERE STUNAME = '서민재';

UPDATE JSSTU 
SET MERRY = 1
WHERE STUNAME = '오형록';


SELECT * FROM JSSTU WHERE MERRY IS NOT NULL;

--4)
SELECT STUNAME FROM JSSTU
WHERE STUPHONE LIKE '__8%' AND STUPHONE LIKE '___8%';

--5) 
SELECT * FROM JSSTU 
WHERE STUNAME NOT LIKE '%민%' AND STUAGE <='25';

--2조
--1)
SELECT STUNAME AS 이름, MERRY AS 결혼, STUAGE AS 나이 FROM JSSTU 
WHERE STUAGE>=24 AND MERRY = 1 AND STUNAME LIKE '이%';

--2)
SELECT * FROM JSSTU 
WHERE STUPHONE LIKE '___3%';

--3)
SELECT * FROM JSSTU
WHERE STUAGE >= 26 AND STUNAME LIKE '이%'
ORDER BY STUNAME ASC;

--4)
SELECT STUAGE,STUAGE+5 AS "5년후",STUNAME FROM JSSTU
WHERE STUAGE+5 >= 30
ORDER BY STUAGE ASC;

--5)
SELECT STUNAME AS 이름, STUAGE AS 나이, STUNO AS 번호, GROUPNO AS 조, STUPHONE AS 전화번호,
STUBIRTH AS 생년월일, SHOESE AS 신발사이즈, MERRY AS 결혼 FROM JSSTU
WHERE STUBIRTH LIKE '_____01%' OR STUBIRTH LIKE '_____02%'
ORDER BY STUAGE DESC;

--3조
--1)
SELECT *
FROM JSSTU 
WHERE GROUPNO = 3 AND STUBIRTH >= 19970000 AND STUBIRTH <= 20010000;

--2)
SELECT *
FROM JSSTU
WHERE STUPHONE LIKE '%11%' OR
STUPHONE LIKE '%22%'OR
STUPHONE LIKE '%33%'OR
STUPHONE LIKE '%44%'OR
STUPHONE LIKE '%55%'OR
STUPHONE LIKE '%66%'OR
STUPHONE LIKE '%77%'OR
STUPHONE LIKE '%88%'OR
STUPHONE LIKE '%99%';

--3)
SELECT * FROM JSSTU
WHERE STUNAME LIKE '%은%'AND STUAGE BETWEEN 23 AND 27;

--4)
SELECT * FROM JSSTU WHERE STUBIRTH LIKE '%11';

--5)
SELECT * FROM JSSTU
WHERE STUBIRTH LIKE '1997%'
ORDER BY STUBIRTH ASC;

--4조
--1)
ALTER TABLE JSSTU ADD GENDER NVARCHAR2(1);


UPDATE JSSTU
SET GENDER = '여'
WHERE STUNAME = '유현서';

UPDATE JSSTU
SET GENDER = '남'
WHERE STUNAME = '이재홍';

UPDATE JSSTU
SET GENDER = '남'
WHERE STUNAME = '오형록';

UPDATE JSSTU
SET GENDER = '남'
WHERE STUNAME = '서민재';

SELECT * FROM JSSTU WHERE GENDER = '남';


--2) 
SELECT * FROM JSSTU
WHERE STUPHONE BETWEEN '2' AND '5'
ORDER BY STUPHONE ASC;

--3)
SELECT * FROM JSSTU
WHERE STUAGE = 25 AND NOT GROUPNO = 1; 

--4)
ALTER TABLE JSSTU ADD STURIDE NVARCHAR2(1);
SELECT * FROM JSSTU;


UPDATE JSSTU
SET STURIDE = 1
WHERE STUNAME = '이재홍';

UPDATE JSSTU
SET STURIDE = 1
WHERE STUNAME = '오형록';

UPDATE JSSTU
SET STURIDE = 0
WHERE STUNAME = '유현서';

UPDATE JSSTU
SET STURIDE = 0 
WHERE STUNAME = '서민재';

SELECT * FROM JSSTU
WHERE GROUPNO = 6;

--5)
SELECT * FROM JSSTU
WHERE GENDER = '남' OR GENDER = '여' AND GENDER IS NULL
ORDER BY GENDER ASC;

--5조
--1)
SELECT * FROM JSSTU
WHERE STUBIRTH LIKE '______6%';
--2)
SELECT * FROM JSSTU WHERE STUNO LIKE '%0_'OR STUNO LIKE '%1_' OR STUNO LIKE '%20';

--3)
SELECT * FROM JSSTU WHERE NOT STUPHONE LIKE '%1%' AND NOT STUPHONE LIKE '%2%'
AND NOT STUPHONE LIKE '%3%' AND NOT STUPHONE LIKE '%3%' AND NOT STUPHONE LIKE '%4%'
AND NOT STUPHONE LIKE '%5%';

--4)
SELECT * FROM  JSSTU WHERE STUNAME LIKE '__';

--5)
SELECT * FROM JSSTU WHERE STUNAME LIKE '이%' AND STUAGE = 25;


--6조

--1)1,2,3조 중에 26살 이하 학생번호가 20번인 사람
SELECT * 
FROM JSSTU
WHERE GROUPNO IN (1,2,3) AND STUAGE <= '26' AND STUNO LIKE '__20'; 

--2)성이 김,이가 아닌 사람중에서 이름에 두번째가 '현'이 들어가는 생일이 1월인 사람 
SELECT * FROM JSSTU 
WHERE(STUNAME NOT LIKE'김%' AND STUNAME NOT LIKE'이%') 
AND STUNAME LIKE '_현%' AND STUBIRTH LIKE '_____01%'; 

--3)2,4,6 조 중에 전화번호 첫번째가 5이면서 92년생인 사람
SELECT * FROM JSSTU
WHERE GROUPNO IN (2,4,6) AND STUPHONE LIKE '5%' AND STUBIRTH LIKE '__92%';

--4)1,2,5,6 중에 25살 이상인 학생 중에 학생번호가 20번 이하이고 
--4월생인 사람중에 전화번호에 5가 들어가는 사람
SELECT * FROM JSSTU
WHERE GROUPNO IN (1,2,5,6) AND STUAGE >= 25 AND STUNO <= 6320 AND STUBIRTH LIKE '_____04%' AND STUPHONE LIKE '%5%'; 

--5)