--사용자 서버에 접속
CREATE USER JS001
IDENTIFIED BY "1111";

CREATE USER JS002
IDENTIFIED BY "1111";

CREATE USER JS003
IDENTIFIED BY "1111";

GRANT CONNECT TO JS001;
GRANT CONNECT TO JS002;
GRANT CONNECT TO JS003;

CREATE TABLE STUDENT(STU_NAME NVARCHAR2(5));
 
INSERT INTO STUDENT VALUES('유현서');
INSERT INTO STUDENT VALUES('이재홍');
INSERT INTO STUDENT VALUES('서민재');
INSERT INTO STUDENT VALUES('오형록');

 COMMIT;
 
 GRANT ALL ON STUDENT TO JS001;
 GRANT ALL ON STUDENT TO JS002;
 GRANT ALL ON STUDENT TO JS003;
 
 SELECT * FROM ALL_USERS;
 
 --서버용(잠금/잠금해제) 

ALTER USER JS001 ACCOUNT LOCK;
ALTER USER JS002 ACCOUNT LOCK;
ALTER USER JS003 ACCOUNT LOCK;

ALTER USER JS001 ACCOUNT UNLOCK;
ALTER USER JS002 ACCOUNT UNLOCK;
ALTER USER JS003 ACCOUNT UNLOCK;

ALTER USER JS001 IDENTIFIED BY "1234";
ALTER USER JS002 IDENTIFIED BY "4567";
ALTER USER JS003 IDENTIFIED BY "7894";
 
 
