
DROP TABLE BANK;

CREATE TABLE BANK(
CLIENTNUMBER NUMBER(10),
NAME NVARCHAR2(10),
ACCOUNTNUMBER NVARCHAR2(20),
BALANCE NUMBER(15),
CONSTRAINT BA_CN_PK PRIMARY KEY (CLIENTNUMBER)
);
SELECT COUNT(*) FROM BANK;

SELECT * FROM BANK;