--13번 문제
SELECT * FROM EMP 
ORDER BY JOB DESC,ENAME ASC;
--14번 문제
SELECT * FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;
--15번 문제
SELECT * FROM EMP
WHERE TO_CHAR(HIREDATE,'YYYYMMHH')>
(SELECT TO_CHAR(HIREDATE,'YYYYMMHH')FROM EMP WHERE ENAME = 'CLARK');


