
--<팀과제>--
/*
  주문 시스템 설계
  
  ENTITY 
  1. SELLER(판매자)
  - 사업자 등록 번호, 상호, 대표자
  
  2. GOODS(상품)
  - 상품코드, 상품 이름, 가격, 재고
  
  3. BUYER(구매자)
  - 아이디, 비밀번호, 이름, 연락처
  
  - 각각 알맞은 제약 조건 설정하기
  - 설정한 테이블에 맞춰 데이터 삽입하기

*/
DROP TABLE SELLER;
DROP TABLE GOODS;
DROP TABLE BUYER;

    CREATE TABLE SELLER(
    SE_CODE NVARCHAR2(20),
    B_NUM NVARCHAR2(20),
    S_NAME NVARCHAR2(20),
    CEO NVARCHAR2(5) DEFAULT '이재홍',
    CONSTRAINT SE_CO_PK PRIMARY KEY(SE_CODE),
    CONSTRAINT SE_CO_FK FOREIGN KEY(SE_CODE) REFERENCES GOODS(GD_CODE)
);

SELECT * FROM SELLER; --★★★★★★
INSERT INTO SELLER VALUES ('01','012-34-56789', 'LONGCAT', DEFAULT);
INSERT INTO SELLER VALUES ('02','012-34-56789', 'LONGCAT','유현서');
-----------------------------------------------------------------------

    CREATE TABLE GOODS(
    GD_CODE NVARCHAR2(10),
    GO_NAME NVARCHAR2(20),
    GD_PRICE NVARCHAR2(20),
    GD_STOCK NVARCHAR2(20),  
    CONSTRAINT GO_GD_PK PRIMARY KEY(GD_CODE)
);

SELECT * FROM GOODS; --★★★★★★

INSERT INTO GOODS VALUES ('01','로얄캐닌', '33000원', '20개');
INSERT INTO GOODS VALUES ('02','아메리칸솔루션', '20000원', '10개');
INSERT INTO GOODS VALUES ('03','조립식 캣타워', '50000원', '30개');

----------------------------------------------------------

  CREATE TABLE BUYER(
    B_CODE NVARCHAR2(20),
    B_ID NVARCHAR2(20)PRIMARY KEY,
    B_PW NUMBER(4) DEFAULT 1234,
    B_NAME NVARCHAR2(20) NOT NULL,
    B_PHNOE NVARCHAR2(20) NOT NULL,
    
    CONSTRAINT JS_PS_CK CHECK(LENGTH(B_PW) =4),
    CONSTRAINT BU_CO_PK PRIMARY KEY(B_CODE),
    CONSTRAINT BU_CD_FK FOREIGN KEY(B_CODE) REFERENCES GOODS(GD_CODE)
);

SELECT * FROM BUYER; --★★★★★★

INSERT INTO BUYER VALUES ('01','MINJ',1234, '서민재','7954');
INSERT INTO BUYER VALUES ('02','SEOO',1234, '유현서','1234');
INSERT INTO BUYER VALUES ('03','JH', DEFAULT , '이재홍','4321');
INSERT INTO BUYER VALUES (NULL,'OHR',5689, '오형록','5555');
--상품이 없다는 뜻

--상품을 나타내는 GO_CODE
--SELLER 테이블, BUYER 테이블 GO_CODE_FK키 지정
--BUYER 테이블
 ALTER TABLE BUYER  ADD CONSTRAINT BY_CODE_FK FOREIGN KEY(B_CODE)
 REFERENCES GOODS(GD_CODE);
 
--SELLER 테이블
 ALTER TABLE SELLER  ADD CONSTRAINT SE_CODE_FK FOREIGN KEY(SE_CODE)
 REFERENCES GOODS(GD_CODE);









